### ISSUE TITLE
get_result handles double letters wrong

### ISSUE THREAD

**Issue by SuneKJakobsen** [mattdodge/wordle_bot#1]
https://github.com/mattdodge/wordle_bot/blob/0026a1a9da46ea714544115f23795d9e87330bd7/solve_wordle.py#L78

In get_result("tells", "liers") the first "l" should result in Status.wrong_spot, as it does. But the second "l" should give Status.miss because there is only one "l" in liers.

Hope I'm not rude to point it out this way. I'm new on GitHub :)

**Comment by SuneKJakobsen** [comment]
Could be handled by using a list for "others" instead of a string and removing the elements once we use them:
`def get_result(guess, answer):
    """ Given a guess and a known answer, return what the result would be """
    out = [None] * 5
    others = []
    # First build exat matches and totally wrongs
    for pos, ch_guess, ch_answer in zip(range(5), guess, answer):
        if ch_guess == ch_answer:
            out[pos] = Status.correct
        elif ch_guess not in answer:
            out[pos] = Status.miss
            others.append(ch_answer)
        else:
            others.append(ch_answer)

    for pos, ch_guess in enumerate(guess):
        if out[pos]:
            continue
        elif ch_guess in others:
            out[pos] = Status.wrong_spot
            others.remove(ch_guess)
        else:
            out[pos] = Status.miss
    return out`

**Comment by mattdodge** [comment]
Not rude at all! GitHub Issues are exactly where you should point out issues like this that you notice in the code.

I knew something was up with the multiple letter support, I'll have to get this fixed up. I think there's a similar issue with the `get_regex_from_knowns` method too

**Comment by mattdodge** [comment]
This has been fixed in the new [wordle-utils](https://github.com/mattdodge/wordle-utils) repository. Thanks for pointing it out!

Example:
```python
>>> from wordle.core.gameplay import get_result
>>> get_result('tells', 'liers')
[<Result.miss: 0>, <Result.wrong_spot: 1>, <Result.wrong_spot: 1>, <Result.miss: 0>, <Result.correct: 2>]
```
