### ISSUE TITLE
Questions about exhaustive guess function

### ISSUE THREAD

**Issue by purple-emily** [mattdodge/wordle_bot#2]
Can you explain part of you code to me, a little better.

I understand the frequency counting, but I am lost when you introduce the `make_guess_exhaustive` method in your [blog post](https://mattdodge.codes/wordle-bot/).

I have forked someone elses repository for a wordle bot and rewritten it myself, so I understand the code. It uses frequency counting. When trying to solve the word `light` I get stuck in the loop like your `atch` example in your code.

I simply don't understand what your exhaustive search function is doing, or how to replicate it myself.

**Comment by mattdodge** [comment]
I've ended up moving this code and cleaning it up to a new repository. The exhaustive guess algorithm is [in that repository](https://github.com/mattdodge/wordle-utils/blob/master/wordle/guess/exhaustive.py) and has a few more comments. Hopefully that helps explain it a bit better, the first version of this code was a bit cluttered. If you have additional questions feel free to drop them in the new [wordle-utils](https://github.com/mattdodge/wordle-utils) repository, thanks!
